@extends('layouts.admin')

@section('title', 'Invoices - CHIBO BRAND')

@section('content')
<div class="container-fluid py-4">
    <div class="row mb-4 d-print-none">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <h2 class="fw-bold mb-1"><i class="fas fa-file-invoice text-info me-2"></i>Invoices</h2>
                    <p class="text-muted mb-0">View and manage all invoices</p>
                </div>
                <div>
                    <button class="btn btn-danger me-2" onclick="exportPDF()">
                        <i class="fas fa-file-pdf me-1"></i> Export PDF
                    </button>
                    <button class="btn btn-success" onclick="exportCSV()">
                        <i class="fas fa-file-csv me-1"></i> Export CSV
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="card-header bg-danger py-3">
            <h6 class="m-0 font-weight-bold text-white">Invoices List</h6>
        </div>
        <div class="card-body">
            <!-- Search Filter -->
            <div class="mb-4 d-print-none">
                <form action="{{ route('admin.payments.invoices') }}" method="GET" class="row g-2 align-items-end">
                    <div class="col-md-6 col-lg-4">
                        <label class="form-label small fw-bold mb-1">Search Order Code/Customer</label>
                        <div class="input-group">
                            <span class="input-group-text bg-white border-end-0"><i class="fas fa-search text-muted"></i></span>
                            <input type="text" name="search" class="form-control border-start-0" placeholder="Enter order code or name..." value="{{ request('search') }}">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="d-flex gap-2">
                            <button type="submit" class="btn btn-primary px-4">Filter</button>
                            @if(request()->filled('search'))
                                <a href="{{ route('admin.payments.invoices') }}" class="btn btn-outline-secondary" title="Reset"><i class="fas fa-undo"></i></a>
                            @endif
                        </div>
                    </div>
                </form>
            </div>

            <!-- Print Header -->
            <div class="print-header d-none text-center mb-4">
                <div class="d-flex justify-content-center align-items-center mb-3">
                    @include('partials.logo-print', ['logoStyle' => 'height:60px;margin-right:15px;object-fit:contain;'])
                    <div class="text-start">
                        <h2 class="fw-bold fs-3 mb-0 text-dark">CHIBO BRANDS CO.LTD</h2>
                        <p class="mb-0 text-muted small">Sales & Inventory Management System</p>
                    </div>
                </div>
                <div class="row mb-3 pb-3 border-bottom">
                    <div class="col-6 text-start">
                        <h5 class="fw-bold mb-1">Report: Invoices List</h5>
                        <small class="text-muted">Generated by: {{ auth()->user()->name }}</small>
                    </div>
                    <div class="col-6 text-end">
                        <h5 class="fw-bold mb-1">Date: {{ now()->format('d M Y') }}</h5>
                        <small class="text-muted">Time: {{ now()->format('H:i') }}</small>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover align-middle">
                    <thead class="bg-danger text-white">
                        <tr>
                            <th scope="col">Invoice #</th>
                            <th scope="col">Order Code</th>
                            <th scope="col">Customer</th>
                            <th scope="col">Total Amount</th>
                            <th scope="col">Amount Paid</th>
                            <th scope="col">Balance</th>
                            <th scope="col">Date</th>
                            <th scope="col">Status</th>
                            <th scope="col" class="d-print-none">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($orders as $order)
                        <tr>
                            <td><strong>INV-{{ str_pad($order->id, 5, '0', STR_PAD_LEFT) }}</strong></td>
                            <td>{{ $order->order_code }}</td>
                            <td>{{ $order->user->name }}</td>
                            <td><strong>TZS {{ number_format($order->total_amount, 0) }}</strong></td>
                            <td class="text-primary"><strong>TZS {{ number_format($order->amount_paid ?: $order->total_amount, 0) }}</strong></td>
                            <td class="{{ $order->balance > 0 ? 'text-danger' : 'text-success' }}">
                                <strong>TZS {{ number_format($order->balance, 0) }}</strong>
                            </td>
                            <td>{{ $order->created_at->format('M d, Y') }}</td>
                            <td>
                                @if($order->payment_status === 'paid')
                                    <span class="badge bg-success">Paid</span>
                                @elseif($order->payment_status === 'partial')
                                    <span class="badge bg-warning text-dark">Partial</span>
                                @else
                                    <span class="badge bg-danger">Pending</span>
                                @endif
                            </td>
                            <td class="d-print-none">
                                <button type="button" class="btn btn-sm btn-outline-primary me-1" onclick="viewOrder({{ $order->id }})" title="View Order">
                                    <i class="fas fa-eye"></i> View
                                </button>
                                <button class="btn btn-sm btn-outline-info" onclick="printInvoice({{ $order->id }})">
                                    <i class="fas fa-print"></i> Print
                                </button>

                                @if($order->balance > 0)
                                    <button type="button" class="btn btn-sm btn-outline-success ms-1" onclick="openPaymentModal({{ $order->id }}, {{ $order->balance }}, '{{ $order->order_code }}')" title="Add Payment">
                                        <i class="fas fa-money-bill-wave"></i> Pay
                                    </button>
                                @endif

                                @if($templates->count() > 0 && ($order->user && $order->user->phone))
                                    <div class="btn-group" role="group">
                                        <button type="button" class="btn btn-sm btn-outline-info dropdown-toggle ms-1" data-bs-toggle="dropdown" aria-expanded="false" title="Send Template">
                                            <i class="fas fa-paper-plane"></i>
                                        </button>
                                        <ul class="dropdown-menu dropdown-menu-end shadow border-0" style="font-size: 0.8rem; min-width: 180px;">
                                            <li class="dropdown-header fw-bold text-uppercase x-small">Send Template</li>
                                            @foreach($templates as $template)
                                                <li>
                                                    <form action="{{ route('admin.message-templates.send') }}" method="POST">
                                                        @csrf
                                                        <input type="hidden" name="template_id" value="{{ $template->id }}">
                                                        <input type="hidden" name="customer_id" value="{{ $order->user->customer_id ?? \App\Models\Customer::where('phone', $order->user->phone)->first()?->id }}">
                                                        <button type="submit" class="dropdown-item py-2" data-no-global-handler>
                                                            <i class="fas fa-comment-alt me-2 text-info opacity-50"></i>{{ $template->title }}
                                                        </button>
                                                    </form>
                                                </li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="9" class="text-center py-5 text-muted">
                                <i class="fas fa-inbox fa-3x mb-3 opacity-25"></i>
                                <p class="mb-0">No invoices found.</p>
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            <div class="d-flex justify-content-between align-items-center mt-3">
                <div class="text-muted">
                    Showing {{ $orders->firstItem() ?? 0 }} to {{ $orders->lastItem() ?? 0 }} of {{ $orders->total() }} entries
                </div>
                <div>
                    {{ $orders->links('pagination::bootstrap-5') }}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- View Order Modal -->
<div class="modal fade" id="viewOrderModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title">Order Details <span id="view_order_code_title"></span></h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="viewOrderModalBody">
                <div class="text-center py-5">
                    <div class="spinner-border text-primary" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
    </div>
</div>

<!-- Payment Modal -->
<div class="modal fade" id="paymentModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form id="paymentForm" method="POST">
                @csrf
                @method('PUT')
                <div class="modal-header bg-success text-white">
                    <h5 class="modal-title"><i class="fas fa-money-bill-wave me-2"></i>Record Payment</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-info py-2 mb-3">
                        <small><i class="fas fa-info-circle me-1"></i> Recording payment for Order: <strong id="paymentOrderCode"></strong></small>
                    </div>
                    
                    <div class="mb-3">
                        <label class="form-label fw-bold">Outstanding Balance</label>
                        <div class="input-group">
                            <span class="input-group-text">TZS</span>
                            <input type="text" class="form-control" id="displayBalance" readonly>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="amount" class="form-label fw-bold">Amount to Pay <span class="text-danger">*</span></label>
                        <div class="input-group">
                            <span class="input-group-text">TZS</span>
                            <input type="number" class="form-control" id="paymentAmount" name="amount" min="1" step="1" required>
                        </div>
                        <div class="form-text">Max payble: <span id="maxPaymentText"></span></div>
                    </div>

                    <div class="mb-3">
                        <label for="payment_method" class="form-label fw-bold">Payment Method <span class="text-danger">*</span></label>
                        <select class="form-select" id="paymentMethod" name="notes" required>
                            <option value="Cash">Cash</option>
                            <option value="Mobile Money">Mobile Money (M-Pesa, Tigo Pesa, etc)</option>
                            <option value="Bank Transfer">Bank Transfer</option>
                            <option value="Card">Credit/Debit Card</option>
                        </select>
                        <div class="form-text">This will be appended to the notes.</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success"><i class="fas fa-check me-1"></i> Confirm Payment</button>
                </div>
            </form>
        </div>
    </div>
</div>

@push('styles')
<style>
@media print {
    /* Hide layout elements */
    .sidebar, .top-navbar, .mobile-menu-toggle, footer, .main-footer { display: none !important; }
    
    /* Hide UI controls */
    .btn, .pagination, .dataTables_filter, .dataTables_length, .card-header, .alert, .modal, .d-print-none { display: none !important; }
    
    /* Reset layout margins */
    .content-wrapper, .main-panel, .content, .main-content { 
        margin-left: 0 !important; 
        padding: 0 !important; 
        width: 100% !important; 
    }
    
    /* Show Print Header */
    .print-header { display: block !important; }
    
    /* Table Styling */
    .table { width: 100% !important; border-collapse: collapse !important; }
    .table th, .table td { 
        border: 1px solid #ddd !important; 
        padding: 6px !important; 
        color: #000 !important;
        font-size: 12px;
    }
    .table thead {
        background-color: #dc3545 !important; 
        color: white !important;
        -webkit-print-color-adjust: exact; 
        print-color-adjust: exact;
    }
    a { text-decoration: none !important; color: #000 !important; }
    
    @page { margin: 10mm; size: auto; }
}
</style>
@endpush

@push('scripts')
<script>
function exportPDF() { window.print(); }
function exportCSV() {
    const table = document.querySelector('table');
    let csv = [];
    const rows = table.querySelectorAll('tr');
    for (let row of rows) {
        const cols = row.querySelectorAll('td, th');
        const csvRow = [];
        for (let col of cols) {
            if (!col.classList.contains('d-print-none')) {
                csvRow.push('"' + col.innerText.replace(/"/g, '""') + '"');
            }
        }
        csv.push(csvRow.join(','));
    }
    const csvFile = new Blob([csv.join('\n')], { type: 'text/csv' });
    const downloadLink = document.createElement('a');
    downloadLink.download = `invoices_${new Date().toISOString().slice(0,10)}.csv`;
    downloadLink.href = window.URL.createObjectURL(csvFile);
    downloadLink.style.display = 'none';
    document.body.appendChild(downloadLink);
    downloadLink.click();
}

function formatCurrency(amount) {
    return 'TZS ' + new Intl.NumberFormat('en-US', {
        minimumFractionDigits: 0,
        maximumFractionDigits: 0
    }).format(amount);
}

function viewOrder(id) {
    const modalEl = document.getElementById('viewOrderModal');
    const modalTitle = document.getElementById('view_order_code_title');
    const modalBody = document.getElementById('viewOrderModalBody');
    const modal = new bootstrap.Modal(modalEl);
    
    modalTitle.textContent = '';
    modalBody.innerHTML = '<div class="text-center py-5"><div class="spinner-border text-primary" role="status"><span class="visually-hidden">Loading...</span></div></div>';
    
    modal.show();
    
    fetch(`/admin/payments/order-data/${id}`)
        .then(response => response.json())
        .then(data => {
            modalTitle.textContent = ' - ' + data.order_code;
            
            let itemsHtml = data.items.map(item => {
                let variantText = '';
                if(item.variants) {
                    if(Array.isArray(item.variants)) {
                         variantText = item.variants.map(v => `<span class="badge bg-secondary me-1" style="font-size:0.7em">${v.name || v.type || ''}: ${v.value || v.option || ''}</span>`).join('');
                    } else if(typeof item.variants === 'object') {
                         variantText = Object.entries(item.variants).map(([k, v]) => `<span class="badge bg-secondary me-1" style="font-size:0.7em">${k}: ${v}</span>`).join('');
                    }
                }
                
                return `
                <tr>
                    <td>
                        <div class="fw-bold">${item.product.name}</div>
                        <div class="small mt-1">${variantText}</div>
                    </td>
                    <td class="text-center">${item.quantity}</td>
                    <td class="text-end">${formatCurrency(item.price)}</td>
                    <td class="text-end fw-bold">${formatCurrency(item.total)}</td>
                </tr>`;
            }).join('');
            
            modalBody.innerHTML = `
                <div class="row mb-4">
                    <div class="col-md-6">
                        <h6 class="fw-bold text-muted mb-2">Customer Info</h6>
                        <p class="mb-1 fw-bold">${data.user ? data.user.name : 'Walk-in Customer'}</p>
                        <p class="mb-1 small"><i class="fas fa-phone me-1"></i> ${data.user && data.user.phone ? data.user.phone : 'N/A'}</p>
                        ${data.customer ? `<p class="mb-0 small"><i class="fas fa-map-marker-alt me-1"></i> ${data.customer.address || 'N/A'}</p>` : ''}
                    </div>
                    <div class="col-md-6 text-end">
                        <h6 class="fw-bold text-muted mb-2">Payment Status</h6>
                        <span class="badge bg-${data.payment_status === 'paid' ? 'success' : (data.payment_status === 'partial' ? 'warning' : 'danger')} fs-6 mb-2">
                            ${data.payment_status ? data.payment_status.toUpperCase() : 'N/A'}
                        </span>
                        <p class="mb-0 small">Date: ${new Date(data.created_at).toLocaleDateString()}</p>
                    </div>
                </div>
                
                <div class="table-responsive mb-4">
                    <table class="table table-bordered table-sm">
                        <thead class="bg-light">
                            <tr>
                                <th>Item</th>
                                <th class="text-center" width="80">Qty</th>
                                <th class="text-end" width="120">Price</th>
                                <th class="text-end" width="120">Total</th>
                            </tr>
                        </thead>
                        <tbody>${itemsHtml}</tbody>
                        <tfoot class="bg-light fw-bold">
                            <tr>
                                <td colspan="3" class="text-end">Subtotal</td>
                                <td class="text-end">${formatCurrency(data.subtotal || data.total_amount)}</td>
                            </tr>
                            ${data.vat_amount ? `
                            <tr>
                                <td colspan="3" class="text-end">VAT (18%)</td>
                                <td class="text-end">${formatCurrency(data.vat_amount)}</td>
                            </tr>` : ''}
                            <tr>
                                <td colspan="3" class="text-end">Total</td>
                                <td class="text-end">${formatCurrency(data.total_amount)}</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="text-end text-primary">Paid</td>
                                <td class="text-end text-primary">${formatCurrency(data.amount_paid)}</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="text-end text-danger">Balance</td>
                                <td class="text-end text-danger">${formatCurrency(data.balance)}</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                
                ${data.notes ? `
                <div class="alert alert-light border">
                    <h6 class="fw-bold fs-6 mb-2"><i class="fas fa-sticky-note me-1"></i> Payment History & Notes</h6>
                    <pre class="mb-0 small text-muted" style="font-family: inherit; white-space: pre-wrap;">${data.notes}</pre>
                </div>` : ''}
            `;
        })
        .catch(err => {
            console.error(err);
            Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: 'Failed to load order details. Please try again or contact support.',
                confirmButtonColor: '#dc3545'
            });
            modalBody.innerHTML = '<div class="alert alert-danger">Failed to load order details.</div>';
        });
}

async function printInvoice(orderId) {
    try {
        // Fetch order data from API
        const response = await fetch(`/admin/payments/order-data/${orderId}`);
        
        if (!response.ok) {
            throw new Error('Failed to fetch order data');
        }
        
        const orderData = await response.json();
        printReceipt(orderData);
        
    } catch (error) {
        console.error('Error printing invoice:', error);
        Swal.fire({
            icon: 'error',
            title: 'Print Failed',
            text: 'Unable to print receipt. Please try again.',
            confirmButtonColor: '#dc3545'
        });
    }
    }


function openPaymentModal(orderId, balance, orderCode) {
    const modal = new bootstrap.Modal(document.getElementById('paymentModal'));
    const form = document.getElementById('paymentForm');
    const orderCodeEl = document.getElementById('paymentOrderCode');
    const displayBalanceEl = document.getElementById('displayBalance');
    const amountInput = document.getElementById('paymentAmount');
    const maxText = document.getElementById('maxPaymentText');
    
    // Set form action
    form.action = `/admin/payments/${orderId}/update`;
    
    // Update UI
    orderCodeEl.textContent = orderCode;
    displayBalanceEl.value = new Intl.NumberFormat('en-US').format(balance);
    amountInput.max = balance;
    amountInput.value = balance; // Default to full payment
    maxText.textContent = new Intl.NumberFormat('en-US').format(balance) + ' TZS';
    
    modal.show();
}

function printReceipt(data) {
    const receiptWindow = window.open('', '_blank', 'width=400,height=700');
    
    function formatNumber(num) {
        return Math.round(num).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    }
    
    const dateTimeStr = new Date(data.created_at).toLocaleString('en-GB', { 
        day: '2-digit', 
        month: '2-digit', 
        year: 'numeric', 
        hour: '2-digit', 
        minute: '2-digit' 
    }).replace(',', '');
    
    const paymentMethod = (data.notes && data.notes.includes('cash')) ? 'CASH' : 'MOBILE MONEY';
    
    const receiptHtml = `
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                @page { margin: 0; }
                body { font-family: 'Courier New', Courier, monospace; font-size: 13px; padding: 15px; width: 80mm; margin: 0 auto; line-height: 1.2; color: #000; text-transform: uppercase; }
                .center { text-align: center; }
                .header-top { font-weight: bold; font-size: 16px; margin-bottom: 2px; }
                .header-sub { font-size: 11px; margin-bottom: 2px; }
                .sep { border-top: 1px dashed #000; margin: 8px 0; }
                .meta-row { display: flex; margin-bottom: 2px; }
                .meta-label { width: 100px; }
                table { width: 100%; border-collapse: collapse; margin-top: 5px; }
                th { border-bottom: 1px solid #000; text-align: left; padding: 5px 0; font-size: 11px; }
                td { padding: 4px 0; vertical-align: top; font-size: 11px; }
                .total-row { display: flex; justify-content: space-between; margin-top: 4px; font-weight: bold; }
                .total-final { font-size: 16px; border-top: 1px solid #000; padding-top: 5px; margin-top: 5px; }
                .footer-qr { margin: 15px 0; text-align: center; }
                .footer-text { font-size: 11px; line-height: 1.3; }
            </style>
        </head>
        <body>
            <div class="center">
                <div class="header-top">CHIBO BRANDS CO.LTD</div>
                <div class="header-sub">KINONDONI, MWIJUMA ROAD</div>
                <div class="header-sub">DAR ES SALAAM, TANZANIA</div>
                <div class="header-sub">TEL: +255 655 392 319 | +255 711 711 111</div>
                <div class="header-sub">TIN: 142-452-167</div>
            </div>
            
            <div class="sep"></div>
            
            <div class="meta-row"><span class="meta-label">ORDER #:</span> <span>${data.order_code}</span></div>
            <div class="meta-row"><span class="meta-label">DATE:</span> <span>${dateTimeStr}</span></div>
            <div class="meta-row"><span class="meta-label">CUSTOMER:</span> <span>${data.customer?.name || data.user?.name || 'WALK-IN GUEST'}</span></div>
            <div class="meta-row"><span class="meta-label">TEL:</span> <span>${data.customer?.phone || data.user?.phone || 'N/A'}</span></div>
            <div class="meta-row"><span class="meta-label">LOC:</span> <span>${data.customer?.address || 'N/A'}</span></div>
            <div class="meta-row"><span class="meta-label">ISSUED BY:</span> <span>${data.saler?.name || data.user?.name || 'STAFF'}</span></div>
            
            <div class="sep"></div>
            
            <table>
                <thead>
                    <tr>
                        <th style="width: 45%;">ITEM</th>
                        <th style="width: 15%;">QTY</th>
                        <th style="width: 20%; text-align:right;">PRICE</th>
                        <th style="width: 20%; text-align:right;">TOTAL</th>
                    </tr>
                </thead>
                <tbody>
                    ${(data.items || []).map(i => `
                        <tr>
                            <td>${i.product?.name || i.name || 'PRODUCT'}</td>
                            <td>${i.quantity} PCS</td>
                            <td style="text-align:right;">${formatNumber(i.price)}</td>
                            <td style="text-align:right;">${formatNumber(i.total || (i.price * i.quantity))}</td>
                        </tr>
                    `).join('')}
                </tbody>
            </table>
            
            <div class="sep"></div>
            
            <div class="total-row">
                <span>SUBTOTAL:</span>
                <span>${formatNumber(data.subtotal || data.total_amount)} TZS</span>
            </div>
            ${data.vat_amount ? `
            <div class="total-row">
                <span>VAT (18%):</span>
                <span>${formatNumber(data.vat_amount)} TZS</span>
            </div>
            ` : ''}
            <div class="total-row total-final">
                <span>TOTAL:</span>
                <span>${formatNumber(data.total_amount)} TZS</span>
            </div>
            <div class="total-row">
                <span>AMOUNT PAID:</span>
                <span>${formatNumber(data.amount_paid || data.total_amount)} TZS</span>
            </div>
            ${(data.balance && data.balance > 0) ? `
            <div class="total-row" style="color: #d32f2f; font-weight: bold;">
                <span>BALANCE:</span>
                <span>${formatNumber(data.balance)} TZS</span>
            </div>
            ` : ''}
            
            <div style="margin-top: 10px; font-size: 11px;">
                <div>PAYMENT METHOD: ${paymentMethod}</div>
                <div>CHECKED BY: ${data.saler?.name || data.user?.name || 'STAFF'}${data.saler?.phone ? ' (' + data.saler.phone + ')' : ''}</div>
            </div>
            
            <div class="footer-qr">
                <img src="https://api.qrserver.com/v1/create-qr-code/?size=100x100&data=${data.order_code}" width="100">
            </div>
            
            <div class="center footer-text">
                <div>THANK YOU FOR SHOPPING WITH US!</div>
                <div style="font-weight: bold; margin-top: 5px; font-size: 11px;">“CREATIVITY MEETS TECHNOLOGY”</div>
                <div style="margin-top: 5px;">GOODS SOLD ARE NOT RETURNABLE</div>
                <div style="font-weight: bold; margin-top: 5px;">WWW.CHIBOBRAND.COM</div>
            </div>
        </body>
        </html>
    `;
    
    receiptWindow.document.write(receiptHtml);
    receiptWindow.document.close();
    receiptWindow.onload = () => {
        setTimeout(() => {
            receiptWindow.print();
            setTimeout(() => receiptWindow.close(), 500);
        }, 300);
    };
}
</script>
@endpush
@endsection
